# Generated by Django 5.1.1 on 2024-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_empleado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
