# Generated by Django 5.1.1 on 2024-10-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='Producto',
            new_name='producto',
        ),
    ]
