# Generated by Django 5.1.1 on 2024-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='formato',
            field=models.CharField(max_length=100),
        ),
    ]
