# Generated by Django 5.1.1 on 2024-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0002_alter_reporte_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
