# Generated by Django 5.1.1 on 2024-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0003_reporte_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='code',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
