# Generated by Django 5.1.1 on 2024-10-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spcmapp', '0005_user_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
    ]
